### ISSUE TITLE
Unneeded app?

### ISSUE THREAD

**Issue by swiharta** [nigma/django-easy-pjax#1]
I love the simplicity and DRY'ness of your solution, but I think I'm accomplishing the same effect using Django's built-in `is_ajax` function in the `{% extends %}` tag, a trick I learned here: http://source.mihelac.org/2011/07/13/extending-different-base-template-ajax-requests-dj/745

**Comment by EugeneDae** [comment]
Working link: http://source.mihelac.org/2011/07/13/extending-different-base-template-ajax-requests-dj/

**Comment by JanMalte** [comment]
Just relying on AJAX is fine in simple applications. But maybe you need a difference in an PJAX loading call and a simple AJAX loading call. Something like requesting a new content page vs. requesting a little modal dialog.
