### ISSUE TITLE
do I need to configure server side or change HTTP header

### ISSUE THREAD

**Issue by a1Gupta** [nigma/django-easy-pjax#7]
I am new to pjax and trying to use django-easy-pjax as this:
![screenshot_9](https://cloud.githubusercontent.com/assets/5560733/3977473/880af58a-2839-11e4-8020-5d818342f36b.png)
1.html
![screenshot_14](https://cloud.githubusercontent.com/assets/5560733/3977541/81d1d2a0-283a-11e4-8049-d7e9a12e5078.png)
views.py
![screenshot_15](https://cloud.githubusercontent.com/assets/5560733/3977543/8a62c3fc-283a-11e4-96ef-3d1be124040e.png)
urls.py
![screenshot_16](https://cloud.githubusercontent.com/assets/5560733/3977547/99d5ecba-283a-11e4-8724-d8f5d938d0d3.png)

But this is not working.Do I need to add pjax_base.html or configure HTTP header to make it work? What else do I need to add in pjax_base.html more than base.html if that is required?

**Comment by JanMalte** [comment]
No, there is no need to change anything in an existing application.

You have to configure PJAX to load all links into a PJAX container on your base page:
https://github.com/defunkt/jquery-pjax
